# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/src/lib/framework/sdl/kiss_sdl/jopadan/SDL2_kiss

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/src/lib/framework/sdl/kiss_sdl/jopadan/SDL2_kiss

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/lib/framework/sdl/kiss_sdl/jopadan/SDL2_kiss/CMakeFiles /usr/src/lib/framework/sdl/kiss_sdl/jopadan/SDL2_kiss//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/lib/framework/sdl/kiss_sdl/jopadan/SDL2_kiss/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kiss_example2

# Build rule for target.
kiss_example2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kiss_example2
.PHONY : kiss_example2

# fast build rule for target.
kiss_example2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kiss_example2.dir/build.make CMakeFiles/kiss_example2.dir/build
.PHONY : kiss_example2/fast

#=============================================================================
# Target rules for targets named kiss_example1

# Build rule for target.
kiss_example1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kiss_example1
.PHONY : kiss_example1

# fast build rule for target.
kiss_example1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kiss_example1.dir/build.make CMakeFiles/kiss_example1.dir/build
.PHONY : kiss_example1/fast

#=============================================================================
# Target rules for targets named SDL2_kiss

# Build rule for target.
SDL2_kiss: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_kiss
.PHONY : SDL2_kiss

# fast build rule for target.
SDL2_kiss/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/build
.PHONY : SDL2_kiss/fast

examples/kiss_example1.o: examples/kiss_example1.c.o

.PHONY : examples/kiss_example1.o

# target to build an object file
examples/kiss_example1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kiss_example1.dir/build.make CMakeFiles/kiss_example1.dir/examples/kiss_example1.c.o
.PHONY : examples/kiss_example1.c.o

examples/kiss_example1.i: examples/kiss_example1.c.i

.PHONY : examples/kiss_example1.i

# target to preprocess a source file
examples/kiss_example1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kiss_example1.dir/build.make CMakeFiles/kiss_example1.dir/examples/kiss_example1.c.i
.PHONY : examples/kiss_example1.c.i

examples/kiss_example1.s: examples/kiss_example1.c.s

.PHONY : examples/kiss_example1.s

# target to generate assembly for a file
examples/kiss_example1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kiss_example1.dir/build.make CMakeFiles/kiss_example1.dir/examples/kiss_example1.c.s
.PHONY : examples/kiss_example1.c.s

examples/kiss_example2.o: examples/kiss_example2.c.o

.PHONY : examples/kiss_example2.o

# target to build an object file
examples/kiss_example2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kiss_example2.dir/build.make CMakeFiles/kiss_example2.dir/examples/kiss_example2.c.o
.PHONY : examples/kiss_example2.c.o

examples/kiss_example2.i: examples/kiss_example2.c.i

.PHONY : examples/kiss_example2.i

# target to preprocess a source file
examples/kiss_example2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kiss_example2.dir/build.make CMakeFiles/kiss_example2.dir/examples/kiss_example2.c.i
.PHONY : examples/kiss_example2.c.i

examples/kiss_example2.s: examples/kiss_example2.c.s

.PHONY : examples/kiss_example2.s

# target to generate assembly for a file
examples/kiss_example2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kiss_example2.dir/build.make CMakeFiles/kiss_example2.dir/examples/kiss_example2.c.s
.PHONY : examples/kiss_example2.c.s

src/kiss_draw.o: src/kiss_draw.c.o

.PHONY : src/kiss_draw.o

# target to build an object file
src/kiss_draw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_draw.c.o
.PHONY : src/kiss_draw.c.o

src/kiss_draw.i: src/kiss_draw.c.i

.PHONY : src/kiss_draw.i

# target to preprocess a source file
src/kiss_draw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_draw.c.i
.PHONY : src/kiss_draw.c.i

src/kiss_draw.s: src/kiss_draw.c.s

.PHONY : src/kiss_draw.s

# target to generate assembly for a file
src/kiss_draw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_draw.c.s
.PHONY : src/kiss_draw.c.s

src/kiss_general.o: src/kiss_general.c.o

.PHONY : src/kiss_general.o

# target to build an object file
src/kiss_general.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_general.c.o
.PHONY : src/kiss_general.c.o

src/kiss_general.i: src/kiss_general.c.i

.PHONY : src/kiss_general.i

# target to preprocess a source file
src/kiss_general.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_general.c.i
.PHONY : src/kiss_general.c.i

src/kiss_general.s: src/kiss_general.c.s

.PHONY : src/kiss_general.s

# target to generate assembly for a file
src/kiss_general.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_general.c.s
.PHONY : src/kiss_general.c.s

src/kiss_posix.o: src/kiss_posix.c.o

.PHONY : src/kiss_posix.o

# target to build an object file
src/kiss_posix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_posix.c.o
.PHONY : src/kiss_posix.c.o

src/kiss_posix.i: src/kiss_posix.c.i

.PHONY : src/kiss_posix.i

# target to preprocess a source file
src/kiss_posix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_posix.c.i
.PHONY : src/kiss_posix.c.i

src/kiss_posix.s: src/kiss_posix.c.s

.PHONY : src/kiss_posix.s

# target to generate assembly for a file
src/kiss_posix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_posix.c.s
.PHONY : src/kiss_posix.c.s

src/kiss_widgets.o: src/kiss_widgets.c.o

.PHONY : src/kiss_widgets.o

# target to build an object file
src/kiss_widgets.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_widgets.c.o
.PHONY : src/kiss_widgets.c.o

src/kiss_widgets.i: src/kiss_widgets.c.i

.PHONY : src/kiss_widgets.i

# target to preprocess a source file
src/kiss_widgets.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_widgets.c.i
.PHONY : src/kiss_widgets.c.i

src/kiss_widgets.s: src/kiss_widgets.c.s

.PHONY : src/kiss_widgets.s

# target to generate assembly for a file
src/kiss_widgets.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2_kiss.dir/build.make CMakeFiles/SDL2_kiss.dir/src/kiss_widgets.c.s
.PHONY : src/kiss_widgets.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SDL2_kiss"
	@echo "... kiss_example1"
	@echo "... kiss_example2"
	@echo "... examples/kiss_example1.o"
	@echo "... examples/kiss_example1.i"
	@echo "... examples/kiss_example1.s"
	@echo "... examples/kiss_example2.o"
	@echo "... examples/kiss_example2.i"
	@echo "... examples/kiss_example2.s"
	@echo "... src/kiss_draw.o"
	@echo "... src/kiss_draw.i"
	@echo "... src/kiss_draw.s"
	@echo "... src/kiss_general.o"
	@echo "... src/kiss_general.i"
	@echo "... src/kiss_general.s"
	@echo "... src/kiss_posix.o"
	@echo "... src/kiss_posix.i"
	@echo "... src/kiss_posix.s"
	@echo "... src/kiss_widgets.o"
	@echo "... src/kiss_widgets.i"
	@echo "... src/kiss_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

